spring:
  application:
    name: ms-relatos-papel-catalogue
  datasource:
    url: jdbc:mysql://localhost:3306/books_catalogue
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd
    time-zone: America/Bogota

server:
  port: 8088

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: 8088
    secure-port-enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always